name: "MakerCAD build"
on:
  pull_request:
  push:
    branches:
      # It's important that the action also runs on merge to main
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # default fetch-depth is insufficent to find previous coverage notes
        fetch-depth: 10
    - uses: marcuswu/makercad-action@6c09743
      with:
        entry: 'main.go'